version: '3'
services:
  lvfox_mariadb:
    image: yoshinorin/docker-mariadb:10.5.4
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: lvfox
    volumes:
      - ./data:/var/lib/mysql
    hostname: lvfox-mariadb
    networks:
      - lvfox
    container_name: lvfox-mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4"]
    restart: unless-stopped
  lvfox:
    image: yoshinorin/docker-lvfox:latest
    environment:
      LVFOX_DB_DATASOURCE_URL: jdbc:mariadb://lvfox-mariadb:3306/lvfox?useUnicode=true&characterEncoding=utf8mb4
      LVFOX_DB_USER: root
      LVFOX_DB_PASSWORD: pass
      LVFOX_SEARCH_TOKEN: test-search-token
      LVFOX_POST_TOKEN: test-post-token
      LVFOX_CORS_ALLOW_ORIGIN: null
      LVFOX_APPLICATION_SECRET: secretpleasechangeme
      SBT_OPTS: "-Xms512M -Xmx768M -Xss2M"
    volumes:
      - ./logs:/usr/opt/lv-fox/logs
    hostname: lvfox
    networks:
      - lvfox
    container_name: lvfox
    ports:
      - "9000:9000"
    command: ["sh", "lv-fox"]
    depends_on:
      - lvfox_mariadb

networks:
  lvfox:
