CREATE TABLE pages (
  url VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  published_at BIGINT UNSIGNED DEFAULT 0,
  updated_at BIGINT UNSIGNED DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
